import React, { useState } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { StoryNode } from '../types';
import { MessageSquare, MessageSquareOff } from 'lucide-react';

interface Props {
  node: StoryNode;
  isLatest?: boolean;
  variant?: 'full' | 'compact' | 'splash';
}

const MangaPanel: React.FC<Props> = ({ node, isLatest = false, variant = 'full' }) => {
  const [showDialogue, setShowDialogue] = useState(true);
  const [imgError, setImgError] = useState(false);

  // Styling variations based on variant
  const isCompact = variant === 'compact';
  const isSplash = variant === 'splash';
  
  const narrativeText = isCompact && node.narrative && node.narrative.length > 220
      ? node.narrative.substring(0, 220) + '...'
      : node.narrative;

  const containerClass = isSplash 
      ? "w-full h-full flex flex-col justify-end relative shadow-[12px_12px_0_0_rgba(0,0,0,1)] border-8 border-black bg-white overflow-hidden" 
      : isCompact 
          ? "w-full h-full flex flex-col relative relative border-4 border-black bg-white overflow-hidden" 
          : `w-full max-w-5xl mx-auto flex flex-col items-center mb-20 ${isLatest ? '' : 'grayscale-[50%] opacity-80'}`;

  const imageAspect = isCompact ? "absolute inset-0 z-0 h-full w-full" : (isSplash ? "absolute inset-0 z-0 h-full w-full" : "relative w-full aspect-[4/3] md:aspect-[16/9] border-8 border-black bg-white overflow-hidden shadow-[12px_12px_0_0_rgba(0,0,0,1)] z-10 flex");

  return (
    <motion.div 
      initial={variant === 'full' ? { opacity: 0, scale: 0.95, y: 50 } : {}}
      animate={variant === 'full' ? { opacity: 1, scale: 1, y: 0 } : {}}
      transition={variant === 'full' ? { duration: 0.6, ease: "easeOut" } : {}}
      className={containerClass}
    >
      {/* Narrative Box - Full & Compact (Outside Image typically, but inside for compact) */}
      {!isSplash && node.narrative && (
        <div className={isCompact ? "relative z-20 bg-white border-b-4 border-black p-3 text-black font-manga-text text-sm leading-tight shadow-[4px_4px_0_0_#000] z-20 m-2 mb-0" : "w-[90%] md:w-[85%] z-20 self-start md:self-center relative top-6"}>
          <div className={isCompact ? "" : "bg-white border-[4px] border-black p-4 md:p-6 text-black font-manga-text text-base md:text-lg leading-relaxed shadow-[8px_8px_0_0_#000]"}>
            {narrativeText}
          </div>
        </div>
      )}

      {/* Main Manga Panel (Image only + Speech Bubble) */}
      <div className={imageAspect}>
        
        {/* Background Image generated by Gemini */}
        {(node.imageUrl && !imgError) ? (
          <img 
            src={node.imageUrl} 
            alt={node.narrative || "Manga scene"} 
            onError={() => setImgError(true)}
            className={`absolute inset-0 w-full h-full object-cover filter grayscale contrast-[1.2] brightness-90 ${isCompact ? 'object-top' : 'pan-slow'}`}
            referrerPolicy="no-referrer"
          />
        ) : (
          <div className="absolute inset-0 bg-gray-900 halftone-bg opacity-50" />
        )}

        {/* Action Indicator */}
        {node.userAction && !isSplash && !isCompact && (
            <div className="absolute top-4 right-4 z-20">
              <div className="inline-block bg-white text-black font-manga-dialogue text-lg px-6 py-3 border-[4px] border-black font-bold uppercase rotate-[-2deg] shadow-[6px_6px_0_0_#000]">
                "{node.userAction}"
              </div>
            </div>
        )}

        {/* Speech Bubble (Overlapping image gracefully) */}
        {node.dialogue && (
          <AnimatePresence>
            {showDialogue ? (
              <motion.div 
                key="dialogue-bubble"
                initial={variant === 'full' ? { scale: 0, opacity: 0 } : {}}
                animate={variant === 'full' ? { scale: 1, opacity: 1 } : {}}
                exit={variant === 'full' ? { scale: 0, opacity: 0 } : {}}
                transition={{ delay: 0.1, type: 'spring', bounce: 0.5 }}
                className={isCompact 
                  ? "absolute bottom-4 right-4 max-w-[85%] z-20"
                  : (isSplash ? "absolute bottom-[30%] right-12 max-w-[50%] z-20" : "absolute bottom-10 right-6 md:right-12 max-w-[65%] md:max-w-[45%] z-20")}
              >
                <div className={`bg-white border-[3px] border-black rounded-[40px] shadow-[4px_4px_0_0_#000] relative speech-bubble-tail ${isCompact ? 'px-4 py-3' : 'px-6 py-5 border-[4px] shadow-[6px_6px_0_0_#000]'}`}>
                  {node.speaker && !isCompact && (
                    <div className="absolute -top-4 -left-3 bg-black text-white text-[11px] uppercase font-bold px-4 py-1.5 border-2 border-white rounded-full tracking-widest shadow-md">
                      {node.speaker}
                    </div>
                  )}
                  <p className={`font-manga-dialogue text-black uppercase leading-tight font-bold ${isCompact ? 'text-xs pr-4' : 'text-lg md:text-xl pr-8'}`}>
                    {isCompact && node.speaker && <span className="block text-[9px] mb-1 opacity-60 tracking-widest">{node.speaker}</span>}
                    {node.dialogue}
                  </p>
                  
                  {/* Hide Button inside Bubble */}
                  {variant === 'full' && (
                  <button 
                    onClick={() => setShowDialogue(false)}
                    className="absolute top-4 right-4 text-gray-400 hover:text-black transition-colors"
                    title="Hide Dialogue"
                  >
                    <MessageSquareOff size={20} />
                  </button>
                  )}
                </div>
              </motion.div>
            ) : variant === 'full' && (
              <motion.button
                key="show-dialogue-btn"
                initial={{ scale: 0, opacity: 0 }}
                animate={{ scale: 1, opacity: 1 }}
                exit={{ scale: 0, opacity: 0 }}
                onClick={() => setShowDialogue(true)}
                className="absolute bottom-10 right-6 md:right-12 z-20 bg-white border-[3px] border-black rounded-full p-4 shadow-[4px_4px_0_0_#000] hover:bg-yellow-200 transition-colors cursor-pointer text-black"
                title="Show Dialogue"
              >
                <MessageSquare size={24} />
              </motion.button>
            )}
          </AnimatePresence>
        )}

        {/* Dramatic VFX Overlays */}
        {isLatest && variant === 'full' && (
          <div className="absolute inset-0 pointer-events-none mix-blend-overlay z-10">
            <div className="w-full h-full shadow-[inset_0_0_80px_rgba(0,0,0,0.6)]" />
          </div>
        )}
      </div>

      {isSplash && node.narrative && (
        <div className="relative z-20 bg-white border-t-8 border-black p-6 w-full shrink-0">
          <p className="font-manga-text text-xl leading-relaxed text-black">{node.narrative}</p>
        </div>
      )}
    </motion.div>
  );
}

export default MangaPanel;

